[tool.poetry]
name = "tinal-poc"
version = "0.1.0"
description = ""
authors = ["Tina Li <tinal@splunk.com>"]

[tool.poetry.dependencies]
python = "3.7"
pytest-splunk-addon = "1.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


