name: build-test-release
on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: 
      - "**"

jobs:
  meta:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Run a one-line script here

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Run a multi-line script here
          echo Hi GDI team, welcome to Tina's Demo
